services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: news_articles
    ports:
      - "5434:5432"  # Changed host port to 5434
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: